
team_sd: 8.0
n_sims: 20000
home_field_pts: 1.5
recent_weight: 0.67  # Reverted from 0.80 - higher weight made predictions worse

# Calibration (dynamic - adjust based on conditions)
score_calibration_factor: 0.85  # Balanced between 0.69 (too low) and 0.95 (too high)

# Betting parameters
bankroll: 10000.0        # Starting bankroll
min_ev: 0.02             # Minimum 2% EV to recommend a bet
kelly_fraction: 0.25     # Use quarter Kelly (25% of full Kelly)
